################################
# Server parameters
################################

server_type: "wsgiref"
host: "127.0.0.1"
port: 8080

################################
# Payout parameters
################################

rate_seconds: 20
koin_payout: 3000000000
k: .5

################################
# Blockchain parameters
################################

rpc_endpoint: ""

################################
# Transaction parameters
################################

wallet_address: ""
private_key_file: "/path/to/private.key"
signing_tool_bin: "/path/to/transaction_signing_tool"
contract_id: ""
entry_point: 0
