################################
# Server parameters
################################

server_type: "wsgiref"
host: "127.0.0.1"
port: 8081

################################
# Payout parameters
################################

token_symbol: "tKOIN"
token_address: "1EdLyQ67LW6HVU1dWoceP4firtyz77e37Y"
rate_seconds: 43200
koin_payout: 1000000000
k: .2

################################
# Blockchain parameters
################################

rpc_endpoint: ""

################################
# Transaction parameters
################################

wallet_file: "/path/to/wallet-file"
wallet_bin: "/path/to/koinos-cli-wallet"
wallet_address: ""
wallet_password: ""
