################################
# Server parameters
################################

server_type: "wsgiref"
host: "127.0.0.1"
port: 8081

################################
# Payout parameters
################################

token_symbol: "tKOIN"
rate_seconds: 43200
koin_payout: 1000000000
k: .2

################################
# Blockchain parameters
################################

rpc_endpoint: ""

################################
# Transaction parameters
################################

wallet_address: ""
private_key_file: "/path/to/private.key"
signing_tool_bin: "/path/to/transaction_signing_tool"
contract_id: ""
balance_of_entry_point: 0x15619248
transfer_entry_point: 0x62efa292
resource_limit: 1000000
